routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// User Routes...
Route::get('/', 'HomeController@allProducts')->name('products.all');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('cart', 'UserCartController');
Route::get('checkout', 'UserCartController@checkout')->name('checkout');
// User Routes End...


// ....Admin Routes Start....
Route::redirect('admin','admin/login');
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', 'Auth\Admin\LoginController@showLoginForm')->name('login');
    Route::get('register', 'Auth\Admin\RegisterController@showRegisterForm')->name('register');
    Route::post('register', 'Auth\Admin\RegisterController@register')->name('register.post');
    Route::post('login', 'Auth\Admin\LoginController@login')->name('login.post');
    Route::post('logout', 'Auth\Admin\LoginController@logout')->name('logout');
    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
});
// ....Admin Routes ENd....

resources/views/cart.blade.php
@extends('layouts.bootstrap')
@section('title')
    All Products
@endsection
@section('content')
<div class="container" style="margin-top: 50px;">
	<div class="container">
	  <div class="row">
	  	<h4>My Cart Items</h4>
	  	<table class="table table-hover">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Name</th>
		      <th scope="col">Qty</th>
		      <th scope="col">Action</th>
		    </tr>
		  </thead>
		  <tbody>
            @forelse($items as $item)
		    <tr>
		      <th scope="row">{{$loop->iteration}}</th>
		      <td>{{$item->product->title}}</td>
		      <td><input type="number" class="qty" data-id="{{$item->id}}" data-product-id="{{$item->product_id}}" name="qty" value="{{$item->qty}}" style="width: 50px;text-align: center;"> </td>
		      <td style="color: red;font-weight:bold;" data-id="{{$item->id}}" id="remove">X</td>
		    </tr>
            @empty
            <tr>
                <td>No Items in your Cart</td>
            </tr>
            @endforelse
		  </tbody>
		</table>
        @if(count($items) > 0)
		<a href="{{route('checkout')}}" class="btn btn-info" style="color: white;">Checkout</a>
        @endif
        <a href="{{route('products.all')}}" class="btn btn-secondary" style="color: white;margin-left: 20px;">Continue Shopping</a>
	  </div>
	</div>
</div>
@endsection

@section('script')
    <script type="text/javascript">
    	$(document).ready(function() {
            $(document).on('click', '#remove', function() {
                var id = $(this).attr('data-id');
                $(this).closest("tr").remove();
                $.ajax({
                    url:'/cart/'+id,
                    type:'POST',
                    dataType:'json',
                    data:{
                        _token:"{{csrf_token()}}",
                        _method:'DELETE',
                    },
                    success:function(res){
                        alert('Item Removed From Cart');
                    }
                    ,error:function(err){
                        alert('Could not delete item');
                    }
                });
            });

            $(document).on('change','.qty',function(){
                var id = $(this).attr('data-id');
                var qty = $(this).val();
                var product_id = $(this).attr('data-product-id');
                $.ajax({
                    url:'/cart/'+id,
                    type:'POST',
                    dataType:'json',
                    data:{
                        _token:"{{csrf_token()}}",
                        _method:'PUT',
                        product_id:product_id,
                        qty:qty
                    },
                    success:function(res){
                        alert('Quantity Updated Successfully');
                    }
                    ,error:function(err){
                        alert('Could not Update Quantity');
                    }
                });
            })
        });
    </script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/products.blade.php
@extends('layouts.bootstrap')
@section('title')
    All Products
@endsection
@section('content')
<div class="container" style="margin-top: 50px;">
	<div class="container">
		@if(Session::has('success'))
			<p class="alert alert-success">{{ Session::get('success') }}</p>
			@endif
	  <div class="row">
	  	@forelse($products as $product)
	    <div class="col-sm">
	      <div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{{asset('images/'.$product->image)}}" alt="Card image cap" style="max-height: 300px;min-height: 300px;">
			  <div class="card-body">
			    <h5 class="card-title">{{$product->title}}</h5>
			    <p class="card-text">{{$product->description}}</p>
			    <p class="card-text">Rs {{$product->price}}</p>
			    <form method="POST" action="{{route('cart.store')}}">
			    	@csrf
			    	<input type="hidden" name="product_id" value="{{$product->id}}">
			    	<input type="hidden" name="qty" value="1">
			    	<button type="submit" class="btn btn-primary btn-block">Add to Cart</button>
			    </form>
			  </div>
			</div>
	    </div>
        @empty
        <tr>
            <td>No Products available. Please login in as Admin and add products.</td>
        </tr>
	    @endforelse
	  </div>
	</div>
</div>
@endsection

@section('style')
	<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">
    	$(document).ready(function() {
            $('#example1').DataTable();
            $(document).on('click', '.deleteUser', function() {
                var id = $(this).attr('data-id');

                swal({
                    title: "Are you sure?",
                    // text: "But you will still be able to retrieve this file.",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, Delete it!",
                    cancelButtonText: "No, cancel please!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, function(isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            url: '/user/' + id,
                            method: 'post',
                            dataType: 'json',
                            data: {
                                "_token": "{{ csrf_token() }}",
                                "_method": 'DELETE',
                                "id": id,
                            },
                            success: function(response) {
                                swal({
                                    title: "User has been deleted successfully",
                                    type: "success"
                                }, function() {
                                    location.reload();
                                });
                            },
                            error: function(err) {
                                console.log(err);
                            }
                        });
                    } else {
                        swal("Cancelled", "Your User is safe :)", "error");
                    }
                });
            });
        });
    </script>
@endsection