routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// User Routes...
Route::get('/', 'HomeController@allProducts')->name('products.all');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('cart', 'UserCartController');
Route::get('checkout', 'UserCartController@checkout')->name('checkout');
// User Routes End...


// ....Admin Routes Start....
Route::redirect('admin','admin/login');
Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('login', 'Auth\Admin\LoginController@showLoginForm')->name('login');
    Route::get('register', 'Auth\Admin\RegisterController@showRegisterForm')->name('register');
    Route::post('register', 'Auth\Admin\RegisterController@register')->name('register.post');
    Route::post('login', 'Auth\Admin\LoginController@login')->name('login.post');
    Route::post('logout', 'Auth\Admin\LoginController@logout')->name('logout');
    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
});
// ....Admin Routes ENd....

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.category.index',['categories'=>Category::orderBy('id','DESC')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('admin.category.index')->with('success','Category added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('admin.category.index')->with('success','Category updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        // $category->delete();
        // return redirect()->route('admin.category.index')->with('success','Category deleted Successfully');

    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.admin')
@section('title')
    Add Category
@endsection
@section('content')
<div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">{{ __('Add Category') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.category.store') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="name" class="form-control @error('name') is-invalid @enderror" name="name" value="" required autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.admin')
@section('title')
    Edit Category
@endsection
@section('content')
<div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">{{ __('Edit Category') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.category.update',$category->id) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="name" class="form-control @error('name') is-invalid @enderror" name="name" value="{{$category->name}}" required autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/category/index.blade.php
@extends('layouts.admin')
@section('title')
    Add Category
@endsection
@section('style')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
@endsection
@section('content')
<div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-md-8">
        	@if(Session::has('success'))
			<p class="alert alert-success">{{ Session::get('success') }}</p>
			@endif
            <div class="card">
                <div class="card-header">{{ __('All Category') }}</div>

                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped">
                    	<thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	@forelse($categories as $category)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$category->name}}</td>
                                <td style="font-size: 18px;display: flex;">
                                    <a class="btn btn-info"  href="{{route('admin.category.edit',$category->id)}}" style="margin-left: 7px" title="Edit"><i class="fa fa-pencil"></i>Edit</a>
                                    <!-- <div style="margin-left: 10px;">
                                    	<form method="POST" action="{{route('admin.category.destroy',$category->id)}}">
	                                    	@csrf
	                        				@method('DELETE')
	                        				<button class="btn btn-danger" type="submit">Delete</button>
	                                    </form>
                                    </div> -->
                                </td>
                            </tr>
                            @empty
                            <tr>
                            	<td>
                            		No Categories Found
                            	</td>
                            	<td></td>
                            	<td></td>
                            </tr>
                            @endforelse
                        </tbody>    
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('style')
	<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">
    	$(document).ready(function() {
            $('#example1').DataTable();
            $(document).on('click', '.deleteUser', function() {
                var id = $(this).attr('data-id');

                swal({
                    title: "Are you sure?",
                    // text: "But you will still be able to retrieve this file.",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, Delete it!",
                    cancelButtonText: "No, cancel please!",
                    closeOnConfirm: false,
                    closeOnCancel: false
                }, function(isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            url: '/user/' + id,
                            method: 'post',
                            dataType: 'json',
                            data: {
                                "_token": "{{ csrf_token() }}",
                                "_method": 'DELETE',
                                "id": id,
                            },
                            success: function(response) {
                                swal({
                                    title: "User has been deleted successfully",
                                    type: "success"
                                }, function() {
                                    location.reload();
                                });
                            },
                            error: function(err) {
                                console.log(err);
                            }
                        });
                    } else {
                        swal("Cancelled", "Your User is safe :)", "error");
                    }
                });
            });
        });
    </script>
@endsection